#!/usr/bin/env python3
import sys, os
from functools import partial
# disable cache usage must be before any local imports
sys.dont_write_bytecode = True

from PyQt6.QtCore import QSettings, QTimer
from PyQt6.QtWidgets import QApplication, QMainWindow, QWidget, QProgressBar
from PyQt6.uic import loadUi

from libmesact import combos
from libmesact import menus
from libmesact import startup
from libmesact import installed
from libmesact import connections

# remove after testing FIXME
from libmesact import tests

VERSION = '3.0.0'
BUILD_DATE = '12/25/2025'

class mesact(QMainWindow):
	def __init__(self):
		super().__init__()

		if os.path.split(sys.argv[0])[0] == '/usr/bin':
			self.lib_path = '/usr/lib/libmesact'
			self.docs_path = '/usr/share/doc/mesact'
			self.installed = True
			loadUi(os.path.join(self.lib_path, 'mesact.ui'), self)
		else:
			srcPath = os.path.split(os.path.realpath(sys.argv[0]))[0]
			self.lib_path = os.path.join(srcPath, 'libmesact')
			self.docs_path = srcPath
			self.installed = False
			loadUi(os.path.join(srcPath, 'mesact.ui'), self)
		stylesheet = os.path.join(self.lib_path, 'mesact.qss')

		with open(stylesheet,'r') as fh:
			self.setStyleSheet(fh.read())

		self.version = VERSION
		self.firmware_path = f'{os.path.expanduser("~")}/.local/lib/libmesact'
		self.settings = QSettings('mesact', 'mesact')
		self.progress_bar = QProgressBar()
		self.statusBar().addPermanentWidget(self.progress_bar)
		self.downloader = None
		self.timer=QTimer()

		self.show()
		startup.setup_vars(self)
		installed.get_versions(self)
		combos.build_combos(self)
		menus.build_menus(self)
		connections.connect(self)
		startup.hide_tabs(self)
		startup.disable_controls(self)
		startup.load_ini(self)
		startup.test(self)

		# remove after testing FIXME
		tests.connect(self)

	def resizeEvent(self, event):
		width = self.geometry().width()
		height =  self.geometry().height()
		self.size_lb.setText(f'{width}x{height}')
		QMainWindow.resizeEvent(self, event)


app = QApplication(sys.argv)
window = mesact()
sys.exit(app.exec())

